language: go

go:
- 1.13

install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- go mod tidy
- git diff
- git diff-index --quiet HEAD --
- go get github.com/kulshekhar/fungen
- go install github.com/kulshekhar/fungen
- go generate ./...

script:
- go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
- bash <(curl -s https://codecov.io/bash)
