[[constraint]]
  name = "github.com/joomcode/errorx"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name ="github.com/couchbaselabs/ghistogram"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
